CREATE DATABASE RPPBA;

CREATE TABLE CLIENT(C_ID INT PRIMARY KEY, O_FNAME CHAR(20), O_LNAME CHAR(20), O_TEL CHAR(20), O_MAIL CHAR(20), L_ID INT);
CREATE TABLE LOYALTY(L_ID INT PRIMARY KEY, L_NAME CHAR(20), L_SALE INT, L_BOUNDARY INT);
CREATE TABLE EMPLOYEE(E_ID INT PRIMARY KEY, E_FNAME CHAR(20), E_LNAME CHAR(20), E_LOGIN CHAR(20), P_ID INT);
CREATE TABLE PASSWORDS(E_ID INT PRIMARY KEY, PASS INT);
CREATE TABLE POSITION(P_ID INT PRIMARY KEY, P_NAME CHAR(20));
CREATE TABLE PRIVILEGE(PR_ID INT PRIMARY KEY, PR_NAME CHAR(20), P_ID INT);
CREATE TABLE PRODUCT(ID INT PRIMARY KEY, MODEL CHAR(20), PRICE INT, TYP INT, K_ID INT, S_ID INT);--????
CREATE TABLE PRODUCTION(DAT DATE, ID INT, KOL INT);
CREATE TABLE RESIDUAL(ID INT PRIMARY KEY, R_KOL INT);
CREATE TABLE KERNEL_FPEN(ID INT PRIMARY KEY, TYP CHAR(20));--?????
CREATE TABLE SHELL_FPEN(ID INT PRIMARY KEY, TYP CHAR(20));
CREATE TABLE KERNEL_FPENCIL(ID INT PRIMARY KEY, TYP CHAR(20));
CREATE TABLE SHELL_FPENCIL(ID INT PRIMARY KEY, TYP CHAR(20));
CREATE TABLE ORDERS(O_ID INT PRIMARY KEY, O_ADR CHAR(30), O_COST INT, O_CONDITION INT, C_ID INT, E_ID INT, D_ID INT);
CREATE TABLE FILLING(O_ID INT, ID INT, F_KOL INT, S_ID INT, DAT DATE);
CREATE TABLE DELIVERY(D_ID INT PRIMARY KEY, D_NAME CHAR(20));
CREATE TABLE STATES(S_ID INT PRIMARY KEY, S_NAME CHAR(20));
CREATE TABLE ACTIONS(A_ID INT PRIMARY KEY, A_NAME CHAR(20));
CREATE TABLE M2_STATES_ACTIONS(A_ID INT, S_ID INT);
CREATE TABLE S13#DAT(DAT DATE PRIMARY KEY, D_KOD INT);
CREATE TABLE S150#NUM(NUM INT);




DROP TABLE EMPLOYEE;